AUE_CITIES=[
  'Accra',
  'Addis Ababa',
  'Ahmedabad',
  'Ahvaz',
  'Alexandria',
  'Algiers',
  'Anqing, Anhui',
  'Antwerp',
  'Arusha',
  'Astrakhan',
  'Auckland',
  'Bacolod',
  'Baghdad',
  'Baku',
  'Bamako',
  'Bangkok',
  'Beijing, Beijing',
  'Beira',
  'Belgaum',
  'Belgrade',
  'Belo Horizonte',
  'Berezniki',
  'Berlin',
  'Bicheng, Chongqing',
  'Bogota',
  'Budapest',
  'Buenos Aires',
  'Bukhara',
  'Busan',
  'Cabimas',
  'Cairo',
  'Caracas',
  'Cebu City',
  'Changzhi, Hunan',
  'Changzhou, Jingsu',
  'Chengdu, Sichuan',
  'Chengguan, Guizhou',
  'Cheonan',
  'Chicago',
  'Cirebon',
  'Cleveland',
  'Cochabamba',
  'Coimbatore',
  'Cordoba',
  'Culiacan',
  'Curitiba',
  'Dhaka',
  'Dzerzhinsk',
  'Florianopolis',
  'Fukuoka',
  'Gainesville, FL',
  'Gaoyou, Jiangsu',
  'Gombe',
  'Gomel',
  'Gorgan',
  'Guadalajara',
  'Guangzhou, Guangdong',
  'Guatemala City',
  'Guixi, Chongqing',
  'Gwangju',
  'Haikou, Hainan',
  'Halle',
  'Hangzhou, Zhejiang',
  'Hindupur',
  'Ho Chi Minh City',
  'Holguin',
  'Hong Kong, Hong Kong',
  'Houston',
  'Hyderabad',
  'Ibadan',
  'Ilheus',
  'Ipoh',
  'Istanbul',
  'Jaipur',
  'Jalna',
  'Jequie',
  'Jinan, Shandong',
  'Jinju',
  'Johannesburg',
  'Kabul',
  'Kaiping, Guangdong',
  'Kairouan',
  'Kampala',
  'Kanpur',
  'Karachi',
  'Kaunas',
  'Kayseri',
  'Khartoum',
  'Kigali',
  'Killeen',
  'Kinshasa',
  'Kolkata',
  'Kozhikode',
  'Lagos',
  'Lahore',
  'Lausanne',
  'Le Mans',
  'Leon',
  'Leshan, Sichuan',
  'London',
  'Los Angeles',
  'Luanda',
  'Lubumbashi',
  'Madrid',
  'Malatya',
  'Malegaon',
  'Manchester',
  'Manila',
  'Marrakesh',
  'Medan',
  'Mexico City',
  'Milan',
  'Minneapolis',
  'Modesto',
  'Montreal',
  'Moscow',
  'Mumbai',
  'Myeik',
  'Nakuru',
  'Ndola',
  'New York',
  'Nikolaev',
  'Okayama',
  'Oldenburg',
  'Osaka',
  'Oyo',
  'Palembang',
  'Palermo',
  'Palmas',
  'Parbhani',
  'Parepare',
  'Paris',
  'Pematangsiantar',
  'Philadelphia',
  'Pingxiang, Jiangxi',
  'Pokhara',
  'Port Elizabeth',
  'Portland, OR',
  'Pune',
  'Pyongyang',
  'Qingdao, Shandong',
  'Qom',
  'Quito',
  'Rajshahi',
  'Raleigh',
  'Rawang',
  'Reynosa',
  'Ribeirao Preto',
  'Riyadh',
  'Rovno',
  'Saidpur',
  'Saint Petersburg',
  'San Salvador',
  'Sana',
  'Santiago',
  'Sao Paulo',
  'Seoul',
  'Shanghai, Shanghai',
  'Sheffield',
  'Shenzhen, Guangdong',
  'Shymkent',
  'Sialkot',
  'Singapore',
  'Singrauli',
  'Sitapur',
  'Springfield, MA',
  'Suining, Sichuan',
  'Suva',
  'Sydney',
  'Taipei, Taiwan',
  'Tangshan, Hebei',
  'Tashkent',
  'Tebessa',
  'Tehran',
  'Tel Aviv',
  'Thessaloniki',
  'Tianjin, Tianjin',
  'Tijuana',
  'Tokyo',
  'Toledo',
  'Tyumen',
  'Ulaanbaatar',
  'Valledupar',
  'Victoria',
  'Vienna',
  'Vijayawada',
  'Vinh Long',
  'Warsaw',
  'Wuhan, Hubei',
  'Xingping, Shaanxi',
  'Xucheng, Jiangsu',
  'Yamaguchi',
  'Yanggu, Shandong',
  'Yiyang, Hunan',
  'Yucheng, Zhejiang',
  'Yulin, Guangxi',
  'Zhengzhou, Henan',
  'Zhuji, Zhejiang',
  'Zunyi, Guizhou',
  'Zwolle',
]
